title: PUENTE Catastral
description: Sistema de modernización catastral con vinculación bidireccional en tiempo real
theme: minima

# GitHub Pages settings
github:
  repository_url: https://github.com/PuenteCatastral/puente-workflows

# Navigation
header_pages:
  - index.md
  - Vinculacion-Tiempo-Real.md
  - Integracion-MuniStream.md
  - URLs-Debug.md

# SEO
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown settings
markdown: kramdown
highlighter: rouge

# Site settings
url: "https://puentecatastral.github.io"
baseurl: "/puente-workflows"

author:
  name: "Equipo PUENTE Catastral"
  email: "puente@example.com"

# Social links
github_username: PuenteCatastral